// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAirEB185_Rqg3pEq-e-PL04d0by0wxGEw',
    appId: '1:1022080076063:web:b4ebb4213f331ed06a482a',
    messagingSenderId: '1022080076063',
    projectId: 'tenafinder-c72de',
    authDomain: 'tenafinder-c72de.firebaseapp.com',
    storageBucket: 'tenafinder-c72de.firebasestorage.app',
    measurementId: 'G-9LJRPL2FH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-lo4OEKk62dCUaUA2fCXkeeTi93pfTTs',
    appId: '1:1022080076063:android:a998860d6cb5fc026a482a',
    messagingSenderId: '1022080076063',
    projectId: 'tenafinder-c72de',
    storageBucket: 'tenafinder-c72de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyRsCAP1_K17-u_TzVW0U21fYQQ_D2I8',
    appId: '1:1022080076063:ios:9af0ef54a885a6286a482a',
    messagingSenderId: '1022080076063',
    projectId: 'tenafinder-c72de',
    storageBucket: 'tenafinder-c72de.firebasestorage.app',
    iosBundleId: 'com.example.tenafinder',
  );
}
